"""initial schema

Revision ID: 19efb82ffbc3
Revises: 
Create Date: 2026-03-13 08:25:50.026445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19efb82ffbc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_ko', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_ko', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('curator_score', sa.Float(), nullable=True),
    sa.Column('curator_reason', sa.Text(), nullable=True),
    sa.Column('curator_detail', sa.JSON(), nullable=True),
    sa.Column('recommended_type', sa.String(), nullable=True),
    sa.Column('recommended_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('used_topic_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['used_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_topics')
    # ### end Alembic commands ###
